
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TicTacToe.java
 *
 * Created on Nov 30, 2014, 11:34:37 AM
 */

/**
 *
 * @author saini
 */
public class TicTacToe extends javax.swing.JFrame {

    /** Creates new form TicTacToe */
    public TicTacToe() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial Unicode MS", 1, 48));
        jTextField1.setForeground(new java.awt.Color(0, 0, 255));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Arial Unicode MS", 1, 48));
        jTextField2.setForeground(new java.awt.Color(0, 0, 255));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Arial Unicode MS", 1, 48));
        jTextField3.setForeground(new java.awt.Color(0, 0, 255));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Arial Unicode MS", 1, 48));
        jTextField4.setForeground(new java.awt.Color(0, 0, 255));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Arial Unicode MS", 1, 48));
        jTextField5.setForeground(new java.awt.Color(0, 0, 255));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Arial Unicode MS", 1, 48));
        jTextField6.setForeground(new java.awt.Color(0, 0, 255));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Arial Unicode MS", 1, 48));
        jTextField7.setForeground(new java.awt.Color(0, 0, 255));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Arial Unicode MS", 1, 48));
        jTextField8.setForeground(new java.awt.Color(0, 0, 255));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Arial Unicode MS", 1, 48));
        jTextField9.setForeground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Now its the Chance of");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel2.setText("Player 1");

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 24));
        jTextField10.setForeground(new java.awt.Color(0, 0, 255));
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jButton1.setForeground(new java.awt.Color(102, 51, 255));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Enter Box Number to Play");

        jLabel4.setText("1");

        jLabel5.setText("2");

        jLabel6.setText("3");

        jLabel7.setText("4");

        jLabel8.setText("6");

        jLabel9.setText("7");

        jLabel10.setText("8");

        jLabel11.setText("9");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 24));
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("Play Virtual Tic Tac Toe");

        jTextField11.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jTextField11.setText("Player 1");
        jTextField11.setEnabled(false);
        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel13.setText("X");

        jTextField12.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jTextField12.setText("Player 2");
        jTextField12.setEnabled(false);
        jTextField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField12MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial Unicode MS", 1, 18));
        jLabel14.setText("O");

        jButton2.setFont(new java.awt.Font("Tahoma", 2, 18));
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Swap");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24));
        jButton3.setForeground(new java.awt.Color(255, 0, 204));
        jButton3.setText("Reset Game");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setText("Player 1");

        jLabel16.setText("Player 2");

        jProgressBar1.setForeground(new java.awt.Color(51, 0, 255));
        jProgressBar1.setMaximum(50);
        jProgressBar1.setStringPainted(true);
        jProgressBar1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBar1StateChanged(evt);
            }
        });

        jProgressBar2.setForeground(new java.awt.Color(0, 204, 0));
        jProgressBar2.setMaximum(50);
        jProgressBar2.setStringPainted(true);
        jProgressBar2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBar2StateChanged(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Arial Black", 1, 18));
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setText("X");
        jButton4.setToolTipText("Click to Close the Game");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bac.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(473, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(13, 13, 13)))))
                .addGap(105, 105, 105))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7, jTextField8, jTextField9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton5, 0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField1)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField2)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addGap(38, 38, 38))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(jLabel3)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addGap(6, 6, 6))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel7)
                        .addGap(175, 175, 175)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField1, jTextField2, jTextField3, jTextField4, jTextField5, jTextField6, jTextField7, jTextField8, jTextField9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField11MouseClicked
jTextField11.selectAll();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11MouseClicked

    private void jTextField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField12MouseClicked
jTextField12.selectAll();        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String x=jLabel2.getText();
        if(x.equals("Player 1")){
            int sl=jProgressBar1.getValue();
 int a=Integer.parseInt(jTextField10.getText());
switch(a){
  case 1 :if(jTextField1.getText().equals("")){
      jTextField1.setText("X");}else{
      JOptionPane.showMessageDialog(null,"Already Marked!");
      }
 break;
  case 2 :if(jTextField2.getText().equals(""))
      jTextField2.setText("X");
  else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 3 :if(jTextField3.getText().equals(""))
      jTextField3.setText("X");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 4 :if(jTextField4.getText().equals(""))
      jTextField4.setText("X");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 5 :if(jTextField5.getText().equals(""))
      jTextField5.setText("X");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 6 :if(jTextField6.getText().equals(""))
      jTextField6.setText("X");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 7 :if(jTextField7.getText().equals(""))
      jTextField7.setText("X");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 8 :if(jTextField8.getText().equals(""))
      jTextField8.setText("X");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 9 :if(jTextField9.getText().equals(""))
      jTextField9.setText("X");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
 default :JOptionPane.showMessageDialog(null,"Wrong Input!");
 break;
}
String j=jTextField1.getText();
String k=jTextField2.getText();
String l=jTextField3.getText();
String m=jTextField4.getText();
String n=jTextField5.getText();
String o=jTextField6.getText();
String p=jTextField7.getText();
String q=jTextField8.getText();
String r=jTextField9.getText();
if(j.equals(k)&&(k.equals(l))&&(l.equals("X"))){
     JOptionPane.showMessageDialog(null,"Player 1 is WINNER ");
 jButton3.doClick();
 if(sl<50){
     jProgressBar1.setValue(sl+=5);
 }
  }else
if(m.equals(n)&&(n.equals(o))&&(o.equals("X"))){
 JOptionPane.showMessageDialog(null,"Player 1 is WINNER ");
 jButton3.doClick();
 if(sl<50){
     jProgressBar1.setValue(sl+=5);
 }
}else
if(p.equals(q)&&(q.equals(r))&&(r.equals("X"))){
 JOptionPane.showMessageDialog(null,"Player 1 is WINNER ");
 jButton3.doClick();
 if(sl<50){
     jProgressBar1.setValue(sl+=5);
 }
}else
if(j.equals(m)&&(m.equals(p))&&(p.equals("X"))){
 JOptionPane.showMessageDialog(null,"Player 1 is WINNER ");
 jButton3.doClick();
 if(sl<50){
     jProgressBar1.setValue(sl+=5);
 }
}else
    if(k.equals(n)&&(n.equals(q))&&(q.equals("X"))){
 JOptionPane.showMessageDialog(null,"Player 1 is WINNER ");
 jButton3.doClick();
 if(sl<50){
     jProgressBar1.setValue(sl+=5);
 }
}else
    if(l.equals(o)&&(o.equals(r))&&(r.equals("X"))){
 JOptionPane.showMessageDialog(null,"Player 1 is WINNER ");
 jButton3.doClick();
 if(sl<50){
     jProgressBar1.setValue(sl+=5);
 }
}else
    if(j.equals(k)&&(k.equals(l))&&(l.equals("X"))){
 JOptionPane.showMessageDialog(null,"Player 1 is WINNER ");
 jButton3.doClick();
 if(sl<50){
     jProgressBar1.setValue(sl+=5);
 }
}else
    if(j.equals(n)&&(n.equals(r))&&(r.equals("X"))){
 JOptionPane.showMessageDialog(null,"Player 1 is WINNER ");
 jButton3.doClick();
 if(sl<50){
     jProgressBar1.setValue(sl+=5);
 }
}else
    if(l.equals(n)&&(n.equals(p))&&(p.equals("X"))){
 JOptionPane.showMessageDialog(null,"Player 1 is WINNER ");
 jButton3.doClick();
 if(sl<50){
     jProgressBar1.setValue(sl+=5);
 }
}
jLabel2.setText("Player 2");

        }else{
int ds=jProgressBar2.getValue();
 int a=Integer.parseInt(jTextField10.getText());

switch(a){
    case 1 :if(jTextField1.getText().equals(""))
        jTextField1.setText("O");
     else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 2 :if(jTextField2.getText().equals(""))
      jTextField2.setText("O");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 3 :if(jTextField3.getText().equals(""))
      jTextField3.setText("O");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 4 :if(jTextField4.getText().equals(""))
      jTextField4.setText("O");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 5 :if(jTextField5.getText().equals(""))
      jTextField5.setText("O");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 6 :if(jTextField6.getText().equals(""))
      jTextField6.setText("O");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 7 :if(jTextField7.getText().equals(""))
      jTextField7.setText("O");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 8 :if(jTextField8.getText().equals(""))
      jTextField8.setText("O");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  case 9 :if(jTextField9.getText().equals(""))
      jTextField9.setText("O");
   else JOptionPane.showMessageDialog(null,"Already Marked!");
 break;
  default :JOptionPane.showMessageDialog(null,"Wrong Input!");
 break;
}
String j=jTextField1.getText();
String k=jTextField2.getText();
String l=jTextField3.getText();
String m=jTextField4.getText();
String n=jTextField5.getText();
String o=jTextField6.getText();
String p=jTextField7.getText();
String q=jTextField8.getText();
String r=jTextField9.getText();
if(j.equals(k)&&(k.equals(l))&&(l.equals("O"))){
 JOptionPane.showMessageDialog(null,"Player 2 is WINNER ");
 jButton3.doClick();
 if(ds<50){
     jProgressBar2.setValue(ds+=5);
 }
}else
if(m.equals(n)&&(n.equals(o))&&(o.equals("O"))){
 JOptionPane.showMessageDialog(null,"Player 2 is WINNER ");
 jButton3.doClick();
 if(ds<50){
     jProgressBar2.setValue(ds+=5);
 }
}else
if(p.equals(q)&&(q.equals(r))&&(r.equals("O"))){
 JOptionPane.showMessageDialog(null,"Player 2 is WINNER ");
 jButton3.doClick();
 if(ds<50){
     jProgressBar2.setValue(ds+=5);
 }
}else
if(j.equals(m)&&(m.equals(p))&&(p.equals("O"))){
 JOptionPane.showMessageDialog(null,"Player 2 is WINNER ");
 jButton3.doClick();
 if(ds<50){
     jProgressBar2.setValue(ds+=5);
 }
}else
    if(k.equals(n)&&(n.equals(q))&&(q.equals("O"))){
 JOptionPane.showMessageDialog(null,"Player 2 is WINNER ");
 jButton3.doClick();
 if(ds<50){
     jProgressBar2.setValue(ds+=5);
 }
}else
    if(l.equals(o)&&(o.equals(r))&&(r.equals("O"))){
 JOptionPane.showMessageDialog(null,"Player 2 is WINNER ");
 jButton3.doClick();
 if(ds<50){
     jProgressBar2.setValue(ds+=5);
 }
}else
    if(j.equals(k)&&(k.equals(l))&&(l.equals("O"))){
 JOptionPane.showMessageDialog(null,"Player 2 is WINNER ");
 jButton3.doClick();
 if(ds<50){
     jProgressBar2.setValue(ds+=5);
 }
}else
    if(j.equals(n)&&(n.equals(r))&&(r.equals("O"))){
 JOptionPane.showMessageDialog(null,"Player 2 is WINNER ");
 jButton3.doClick();
 if(ds<50){
     jProgressBar2.setValue(ds+=5);
 }
}else
    if(l.equals(n)&&(n.equals(p))&&(p.equals("O"))){
 JOptionPane.showMessageDialog(null,"Player 2 is WINNER ");
 jButton3.doClick();
 if(ds<50){
     jProgressBar2.setValue(ds+=5);
 }
}
jLabel2.setText("Player 1");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
  jTextField10.selectAll();
  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jTextField10.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jTextField4.setText("");
jTextField5.setText("");
jTextField6.setText("");
jTextField7.setText("");
jTextField8.setText("");
jTextField9.setText("");
jTextField10.setText("");
jLabel2.setText("Player 1");



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if((jTextField1.getText().equals(""))
        &&
        (jTextField2.getText().equals(""))
        &&
        (jTextField3.getText().equals(""))
        &&
        (jTextField4.getText().equals(""))
        &&
        (jTextField5.getText().equals(""))
        &&
        (jTextField6.getText().equals(""))
        &&
        (jTextField7.getText().equals(""))
        &&
        (jTextField8.getText().equals(""))
        &&
        (jTextField9.getText().equals(""))
        ){
    
    if(jLabel2.getText().equals("Player 1")){
       jLabel2.setText("Player 2");  
    }else{
      jLabel2.setText("Player 1");  
    }
}else
    JOptionPane.showMessageDialog(null,"Swapping is not allowed until game is reseted...");



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jProgressBar1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBar1StateChanged
int a=jProgressBar1.getValue();
if(a==50){
    JOptionPane.showMessageDialog(null, "Player 1 is a Ultimate Winner!");
    jProgressBar1.setValue(0);
}
// TODO add your handling code here:
    }//GEN-LAST:event_jProgressBar1StateChanged

    private void jProgressBar2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBar2StateChanged
  int b=jProgressBar2.getValue();
if(b==50){
    JOptionPane.showMessageDialog(null, "Player 2 is a Ultimate Winner!");
    jProgressBar2.setValue(0);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBar2StateChanged

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
jButton1.doClick();
jTextField10.selectAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.setVisible(false);
new Developer().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
