
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author tanuj
 */
public class Custmz extends javax.swing.JFrame {

    /** Creates new form Custmz */
    public Custmz() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Customize your Account");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Choose Your avatar");

        jList1.setForeground(new java.awt.Color(153, 0, 0));
        jList1.setModel(new javax.swing.AbstractListModel() {
            ImageIcon[] strings={ new ImageIcon("1.jpg"),
                new ImageIcon("2.jpg"),
                new ImageIcon("3.jpg"),
                new ImageIcon("4.jpg"),
                new ImageIcon("5.jpg"),
                new ImageIcon("6.jpg"),
                new ImageIcon("7.jpg"),
                new ImageIcon("8.jpg"),
                new ImageIcon("9.jpg"),
                new ImageIcon("10.jpg"),
                new ImageIcon("11.jpg"),
                new ImageIcon("12.jpg"),
                new ImageIcon("13.jpg"),
                new ImageIcon("14.jpg"),
                new ImageIcon("15.jpg"),
                new ImageIcon("16.jpg"),
                new ImageIcon("17.jpg"),
                new ImageIcon("18.jpg"),
                new ImageIcon("19.jpg"),
                new ImageIcon("20.jpg"),
                new ImageIcon("21.jpg"),
                new ImageIcon("22.jpg"),
                new ImageIcon("23.jpg"),
                new ImageIcon("24.jpg"),
                new ImageIcon("25.jpg"),

            };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("NickName:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Job:");

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField2.setForeground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Hobbies:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Working At:");

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jTextField3.setForeground(new java.awt.Color(0, 102, 102));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jComboBox1.setForeground(new java.awt.Color(0, 102, 102));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Singing", "Dancing", "Listening Music", "Reading", "Cooking", "Painting", "Sports" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rafael-icon.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 0, 51));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, 199, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
String code1=SignUp.jTextField9.getText();
int code=Integer.parseInt(code1);
jLabel7.setText(""+code);

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String user="";
String pass="";
String name="";
int code=Integer.parseInt(jLabel7.getText());
String nick=jTextField1.getText();
String job=jTextField2.getText();
String work=jTextField3.getText();
String hob=(String)jComboBox1.getSelectedItem();
String dp1="";
String dp2="";
int l=jList1.getSelectedIndex();
l++;
switch(l){
    case 1:dp1="1";
    dp2="1a";
    break;
    case 2:dp1="2";
    dp2="2a";
    break;
    case 3:dp1="3";
    dp2="3a";
    break;
    case 4:dp1="4";
    dp2="4a";
    break;
    case 5:dp1="5";
    dp2="5a";
    break;
    case 6:dp1="6";
    dp2="6a";
    break;
    case 7:dp1="7";
    dp2="7a";
    break;
    case 8:dp1="8";
    dp2="8a";
    break;
    case 9:dp1="9";
    dp2="9a";
    break;
    case 10:dp1="10";
    dp2="10a";
    break;
    case 11:dp1="11";
    dp2="11a";
    break;
    case 12:dp1="12";
    dp2="12a";
    break;
    case 13:dp1="13";
    dp2="13a";
    break;
    case 14:dp1="14";
    dp2="14a";
    break;
    case 15:dp1="15";
    dp2="15a";
    break;
    case 16:dp1="16";
    dp2="16a";
    break;
    case 17:dp1="17";
    dp2="17a";
    break;
    case 18:dp1="18";
    dp2="18a";
    break;
    case 19:dp1="19";
    dp2="19a";
    break;
    case 20:dp1="20";
    dp2="20a";
    break;
    case 21:dp1="21";
    dp2="21a";
    break;
    case 22:dp1="22";
    dp2="22a";
    break;
    case 23:dp1="23";
    dp2="23a";
    break;
    case 24:dp1="24";
    dp2="24a";
    break;
    case 25:dp1="25";
    dp2="25a";
    break;
    default: dp1="null1";
    dp2="null2";
}
try{
   String q1="update members set Nickname='"+nick+"', Job='"+job+"', Workingat='"+work+"', Hobbies='"+hob+"', Dpbig='"+dp1+"', Dpsmall='"+dp2+"' where Code="+code+";";
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
    Statement s1=con.createStatement();
    s1.executeUpdate(q1);
    int y=JOptionPane.showConfirmDialog(null,"<html>Account Customization Complete!<br> Do you want to Sign In to your account now?" );
    if(y==JOptionPane.YES_OPTION){
        /*
        try{
   String qu="Select Name,Username,Password from members where Code="+code+";";
    Class.forName("java.sql.Driver");
    Connection co=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
    Statement s=co.createStatement();
    ResultSet rs=s.executeQuery(qu);
         rs.next();
         user=rs.getString("Username");
         pass=rs.getString("Password");
         name=rs.getString("Name");
        }
catch(Exception e){
    JOptionPane.showMessageDialog(null,""+e.getMessage() );
}
         */
try{
   String q="insert into session values("+code+");";
    Class.forName("java.sql.Driver");
    Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
    Statement s=c.createStatement();
   s.executeUpdate(q);
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,""+e.getMessage() );
}
        this.setVisible(false);
        new Home().setVisible(true);
        }
    else
    if(y==JOptionPane.NO_OPTION){
         this.setVisible(false);
        new LogIn().setVisible(true);
                                 }
   }
catch(Exception e){
    JOptionPane.showMessageDialog(null,""+e.getMessage() );
}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Custmz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
