
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author tanuj
 */
public class NewMessage extends javax.swing.JFrame {

    /** Creates new form NewMessage */
    public NewMessage() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setForeground(new java.awt.Color(102, 51, 255));
        jLabel1.setText("New Message");

        jSeparator1.setForeground(new java.awt.Color(255, 51, 51));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jRadioButton1.setForeground(new java.awt.Color(255, 0, 153));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Send Text");
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Text"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Enter Text:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesBTDE7PYK.png"))); // NOI18N
        jButton1.setText("Send>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jButton3.setForeground(new java.awt.Color(102, 0, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bac.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("To:");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jComboBox1.setForeground(new java.awt.Color(51, 153, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Photo"));

        jList1.setModel(new javax.swing.AbstractListModel() {
            ImageIcon[] strings={ new ImageIcon("D:\\ChatApp\\1s.jpg"),
                new ImageIcon("D:\\ChatApp\\2s.png"),
                new ImageIcon("D:\\ChatApp\\3s.jpg"),
                new ImageIcon("D:\\ChatApp\\4s.jpg"),
                new ImageIcon("D:\\ChatApp\\5s.jpg"),
                new ImageIcon("D:\\ChatApp\\6s.jpg"),
                new ImageIcon("D:\\ChatApp\\7s.png"),
                new ImageIcon("D:\\ChatApp\\8s.jpg"),
                new ImageIcon("D:\\ChatApp\\9s.jpg"),
                new ImageIcon("D:\\ChatApp\\10s.jpg"),
                new ImageIcon("D:\\ChatApp\\11s.jpg"),
                new ImageIcon("D:\\ChatApp\\12s.jpg"),
                new ImageIcon("D:\\ChatApp\\13s.jpg"),
                new ImageIcon("D:\\ChatApp\\14s.jpg"),
                new ImageIcon("D:\\ChatApp\\15s.jpg"),
                new ImageIcon("D:\\ChatApp\\16s.jpg"),
                new ImageIcon("D:\\ChatApp\\17s.jpg"),
                new ImageIcon("D:\\ChatApp\\18s.jpg"),
                new ImageIcon("D:\\ChatApp\\19s.jpg"),
                new ImageIcon("D:\\ChatApp\\20s.jpg"),
                new ImageIcon("D:\\ChatApp\\21s.jpg"),
                new ImageIcon("D:\\ChatApp\\22s.jpg"),
                new ImageIcon("D:\\ChatApp\\23s.png"),
                new ImageIcon("D:\\ChatApp\\24s.jpg"),
                new ImageIcon("D:\\ChatApp\\25s.png"),

            };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setEnabled(false);
        jScrollPane1.setViewportView(jList1);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jButton2.setForeground(new java.awt.Color(255, 102, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesR0R4GX80.jpg"))); // NOI18N
        jButton2.setText("Send>>");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 0, 153));
        jRadioButton2.setText("Send Sticker");
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jButton2))
                    .addComponent(jRadioButton2))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(73, 73, 73))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jRadioButton1))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
new Messages().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
jTextField1.requestFocus();
String user="";
String pass="";
int code=0;
//String name="";
try
{
String q="select code, Username,Password from session natural join auth;";
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
Statement s=con.createStatement();
ResultSet r=s.executeQuery(q);
r.next();
user=r.getString("Username");
pass=r.getString("Password");
code=r.getInt("Code");
 //name=r.getString("Name");
 jLabel4.setText(""+code);

 //jLabel5.setText(""+name);
}
catch(Exception e)
{
    e.printStackTrace();
 JOptionPane.showMessageDialog(null,"Please Log in from LogIn Window!");
}



try {
      String q="select User2 as user, (select name from members where code=user) as Name from friendlist where user1="+code+" union select user1 as user, (select name from members where code=user) as Name from friendlist where user2="+code+";";
      Class.forName("java.sql.Driver");
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
      Statement s=con.createStatement();
      ResultSet rs=s.executeQuery(q);
     if(rs.next()){
         rs.previous();
         while(rs.next()){
             String f=rs.getString("Name");
          jComboBox1.addItem(f);
                         }
     }else{
         JOptionPane.showMessageDialog(null,"<html>You don't have Any Friends!<br>You cannot message anyone!");
         jRadioButton1.setEnabled(false);
         jRadioButton2.setEnabled(false);
          jButton1.setEnabled(false);
           jButton2.setEnabled(false);
            jTextField1.setEnabled(false);
             jComboBox1.setEnabled(false);
             jList1.setEnabled(false);
     }

      rs.close();
      s.close();
      con.close();
    } catch(Exception e){
        e.printStackTrace();
      //  JOptionPane.showMessageDialog(null,""+e.getMessage());
                        }

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String kind="text";
String text=jTextField1.getText();
String name1=jLabel5.getText();
String name2=(String)jComboBox1.getSelectedItem();
int code1=Integer.parseInt(jLabel4.getText());

int code2=0;
int se1=0;
int se2=0;
try{
   String q1="Select Code from members where Name='"+name2+"';";
    Class.forName("java.sql.Driver");
    Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
    Statement s1=con1.createStatement();
    ResultSet rs1=s1.executeQuery(q1);
    rs1.next();
    code2=rs1.getInt("Code");
    con1.close();
    s1.close();
    rs1.close();
}
catch(Exception e){
    e.printStackTrace();
    //JOptionPane.showMessageDialog(null,""+e.getMessage() );
}

try{
    String q1="Select Serial from Messages;";
   // String q3="Select Serial from Message"+code2+";";
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
    Statement s1=con.createStatement();
    ResultSet rs1=s1.executeQuery(q1);
    rs1.last();
    se1=rs1.getInt("Serial");
    se1++;
//    Statement s3=con.createStatement();
//    ResultSet rs3=s3.executeQuery(q3);
//    rs3.last();
//    se2=rs3.getInt("Serial");
//    se2++;
           }
catch(Exception e){
    e.printStackTrace();
   // JOptionPane.showMessageDialog(null,""+e.getMessage() );
}

try{
   String q1="insert into Messages values("+se1+",'"+text+"',"+code1+","+code2+",mid(now(),12),0,'"+kind+"');";
  // String q2="insert into Message"+code2+" values("+se2+",'"+text+"','"+name1+"','"+name2+"',mid(now(),12),0,'"+kind+"');";
    Class.forName("java.sql.Driver");
    Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
    Statement s1=con1.createStatement();
    s1.executeUpdate(q1);
//    Statement s2=con1.createStatement();
//    s2.executeUpdate(q2);
    JOptionPane.showMessageDialog(null,"Message Sent Successfully!");
    this.setVisible(false);
    new NewMessage().setVisible(true);
    con1.close();
    s1.close();
  //  s2.close();
}
catch(Exception e){
    e.printStackTrace();
   // JOptionPane.showMessageDialog(null,""+e.getMessage() );
}


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
if(jRadioButton2.isSelected()){
    jButton2.setEnabled(true);
    jButton1.setEnabled(false);
    jList1.setEnabled(true);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
String image="";
String kind="both";
int im=jList1.getSelectedIndex();
im++;
try {
      String q="Select Value from Sendphoto where Serial="+im+";";
      Class.forName("java.sql.Driver");
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
      Statement s=con.createStatement();
      ResultSet rs=s.executeQuery(q);
      rs.next();
      image=rs.getString("Value");
      rs.close();
      s.close();
      con.close();
    } catch(Exception e){
        e.printStackTrace();
       // JOptionPane.showMessageDialog(null,""+e.getMessage());
                        }

String name1=jLabel5.getText();
String name2=(String)jComboBox1.getSelectedItem();
int code1=Integer.parseInt(jLabel4.getText());

int code2=0;
int se1=0;
int se2=0;
try{
   String q1="Select Code from members where Name='"+name2+"';";
    Class.forName("java.sql.Driver");
    Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
    Statement s1=con1.createStatement();
    ResultSet rs1=s1.executeQuery(q1);
    rs1.next();
    code2=rs1.getInt("Code");
    con1.close();
    s1.close();
    rs1.close();
}
catch(Exception e){
    e.printStackTrace();
   // JOptionPane.showMessageDialog(null,""+e.getMessage() );
}

try{
    String q1="Select Serial from Messages;";
   // String q3="Select Serial from Message"+code2+";";
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
    Statement s1=con.createStatement();
    ResultSet rs1=s1.executeQuery(q1);
    rs1.last();
    se1=rs1.getInt("Serial");
    se1++;
//    Statement s3=con.createStatement();
//    ResultSet rs3=s3.executeQuery(q3);
//    rs3.last();
//    se2=rs3.getInt("Serial");
//    se2++;
           }
catch(Exception e){
    e.printStackTrace();
  //  JOptionPane.showMessageDialog(null,""+e.getMessage() );
}

try{
   String q1="insert into Messages values("+se1+",'"+image+"',"+code1+","+code2+",mid(now(),12),0,'"+kind+"');";
  // String q2="insert into Message"+code2+" values("+se2+",'"+image+"','"+name1+"','"+name2+"',mid(now(),12),0,'"+kind+"');";
    Class.forName("java.sql.Driver");
    Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3306/tanuj","root","123");
    Statement s1=con1.createStatement();
    s1.executeUpdate(q1);
//    Statement s2=con1.createStatement();
//    s2.executeUpdate(q2);
    JOptionPane.showMessageDialog(null,"Sticker Sent Successfully!");
    this.setVisible(false);
    new NewMessage().setVisible(true);
    con1.close();
    s1.close();
   // s2.close();
}
catch(Exception e){
    e.printStackTrace();
  //  JOptionPane.showMessageDialog(null,""+e.getMessage() );
}



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
if(jRadioButton1.isSelected()){
    jButton2.setEnabled(false);
     jButton1.setEnabled(true);
     jList1.setEnabled(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMessage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
